// pages/api/detect-text.js
// Detect whether text is AI-generated. Uses OpenAI if available, otherwise falls back to a heuristic.
// Handles OpenAI "insufficient_quota" errors gracefully.

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).end();
  const { text } = req.body || {};
  if (!text) return res.status(400).json({ error: 'No text' });

  const key = process.env.OPENAI_API_KEY;
  // local heuristic helper
  const heuristic = (t) => {
    const words = t.trim().split(/\s+/).filter(Boolean);
    const sentences = t.split(/[.!?]+/).filter(Boolean);
    const repetitive = (t.match(/\b(the the|in the|and the|therefore|thus|moreover)\b/gi) || []).length;
    const avgWordLen = (words.reduce((a,b)=>a+b.length,0)/Math.max(1,words.length));
    const score = Math.min(0.95, 0.05 + repetitive*0.15 + (avgWordLen>6?0.1:0));
    return { ai_probability: parseFloat(score.toFixed(2)), details: { fallback: true, repetitive, avgWordLen } };
  };

  if (!key) {
    // no key configured — immediate fallback
    return res.json(heuristic(text));
  }

  try {
    const prompt = `You are an assistant that evaluates whether a piece of text looks like it was generated by AI. Respond with a JSON object with keys: ai_probability (0.0-1.0) and a short explanation.\n\nText:\n${text}`;
    const resp = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + key },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [{ role: 'user', content: prompt }],
        max_tokens: 200,
        temperature: 0.0
      })
    });
    const data = await resp.json();
    if (data.error) throw data.error;
    const reply = data.choices?.[0]?.message?.content || '';
    // try to extract a number; if not found return whole reply
    const m = reply.match(/ai_probability\\s*[:=]\\s*(0?\\.\\d+|1(\\.0+)?)/i);
    const ai_probability = m ? parseFloat(m[1]) : null;
    res.json({ ai_probability, explanation: reply, raw: data });
  } catch (err) {
    // if OpenAI quota or billing issue, fallback to heuristic
    const code = err?.code || err?.type || '';
    if (code === 'insufficient_quota' || code === 'insufficient_funds' || (err?.message || '').toLowerCase().includes('quota')) {
      return res.json({
        ...heuristic(text),
        note: 'OpenAI quota exceeded — returned heuristic fallback. Please check billing or try later.'
      });
    }
    // other errors: surface limited info, but avoid exposing secret details
    return res.status(500).json({ error: err?.message || 'OpenAI error', raw: err });
  }
}
