    // Detect whether text is AI-generated using OpenAI (chat completion).
    export default async function handler(req, res) {
      if (req.method !== 'POST') return res.status(405).end();
      const { text } = req.body || {};
      if (!text) return res.status(400).json({ error: 'No text' });

      const key = process.env.OPENAI_API_KEY;
      if (!key) {
        // fallback heuristic if no key
        const repetitive = (text.match(/\b(the the|in the|and the|therefore|thus)\b/gi) || []).length;
        return res.json({ ai_probability: Math.min(0.95, 0.1 + repetitive * 0.15), details: { note: 'No OPENAI_API_KEY: using heuristic', repetitive } });
      }

      try {
        const prompt = `You are an assistant that evaluates whether a piece of text looks like it was generated by AI. Respond with a JSON object with keys: ai_probability (0.0-1.0) and explanation.

Text:\n${text}`;
        const resp = await fetch('https://api.openai.com/v1/chat/completions', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + key
          },
          body: JSON.stringify({
            model: 'gpt-4o-mini',
            messages: [{ role: 'user', content: prompt }],
            max_tokens: 200,
            temperature: 0.0
          })
        });
        const data = await resp.json();
        const reply = data.choices?.[0]?.message?.content || '';
        // Try to parse ai_probability from reply; if not present, return reply as explanation.
        let ai_probability = null;
        const m = reply.match(/ai_probability\s*[:=]\s*(0?\.\d+|1(\.0+)?)/i);
        if (m) ai_probability = parseFloat(m[1]);
        res.json({ ai_probability, explanation: reply, raw: data });
      } catch (e) {
        res.status(500).json({ error: e.message });
      }
    }
